# Generated by Django 2.0.13 on 2019-08-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='무슨 생각을 하고 계세요?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='title of message.', max_length=200),
        ),
    ]
