# Generated by Django 2.0 on 2019-09-29 09:02

from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    post = apps.get_model('blog', 'post')
    for p in post.objects.all():
        p.uuid = uuid.uuid4()
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190928_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),

    ]
