# Generated by Django 2.0 on 2019-09-06 08:42

import blog.models
import blog.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190811_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', inverse_match=True, message="Name is reserved: 'new', 'edit' or 'test'.", regex='^(?:new|edit|test|preview)*$')])),
                ('file', models.FileField(unique=True, upload_to=blog.models.upload_to, validators=[blog.utils.FileValidator(allowed_extensions=('jpg', 'png', 'svg', 'gif'), allowed_mimetypes=('image/jpeg', 'image/png', 'image/svg', 'image/svg+xml', 'image/gif'), restricted_basename=False)])),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(blank=True, to='blog.Image'),
        ),
    ]
