# Generated by Django 2.0 on 2019-11-01 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_contributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
