# Generated by Django 2.0 on 2019-09-05 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190827_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='code_language',
        ),
        migrations.RemoveField(
            model_name='post',
            name='code_style',
        ),
        migrations.RemoveField(
            model_name='post',
            name='lineos',
        ),
    ]
