# Generated by Django 2.0 on 2019-09-08 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190906_1742'),
        ('blog', '0008_comment'),
    ]

    operations = [
    ]
