# Generated by Django 2.0 on 2019-09-28 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='filename',
        ),
    ]
