# Generated by Django 2.0 on 2019-11-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_last_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='revision_id',
            field=models.IntegerField(default=0),
        ),
    ]
