# Generated by Django 2.0 on 2019-11-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_revision_revision_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='revision_id',
            field=models.IntegerField(default=1),
        ),
    ]
