# Generated by Django 2.0 on 2019-11-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191109_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='title',
            field=models.CharField(help_text='제목을 입력하세요', max_length=200, null=True),
        ),
    ]
