# Generated by Django 2.0 on 2019-12-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_revision_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='text',
        ),
        migrations.AddField(
            model_name='revision',
            name='current_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='revision',
            name='original_text',
            field=models.TextField(default=''),
        ),
    ]
