"""날짜와 타입으로 기본키를 변경.

Revision ID: b8faa06e6d4d
Revises: f872d8792cf6
Create Date: 2018-07-15 17:38:56.456688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8faa06e6d4d'
down_revision = 'f872d8792cf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('histories', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('histories', sa.Column('id', sa.INTEGER(), primary_key=True))
    # ### end Alembic commands ###
