"""add coin type

Revision ID: f872d8792cf6
Revises: 18dbc1ecc598
Create Date: 2018-07-09 21:37:44.714234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f872d8792cf6'
down_revision = '18dbc1ecc598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('histories', sa.Column('coin_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('histories', 'coin_type')
    # ### end Alembic commands ###
