"""empty message

Revision ID: 0570d3a2eb59
Revises: 3a2c9adc232b
Create Date: 2018-12-30 21:25:44.848824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0570d3a2eb59'
down_revision = '3a2c9adc232b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('director', sa.Column('movie_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'director', 'movie', ['movie_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'director', type_='foreignkey')
    op.drop_column('director', 'movie_id')
    # ### end Alembic commands ###
