"""empty message

Revision ID: 3a2c9adc232b
Revises: 3cc1a1982fb1
Create Date: 2018-12-30 18:48:42.212213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a2c9adc232b'
down_revision = '3cc1a1982fb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_with_director',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('director_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['director_id'], ['director.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], )
    )
    op.drop_table('director_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('director_association',
    sa.Column('movie_id', sa.INTEGER(), nullable=True),
    sa.Column('director_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['director_id'], ['director.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], )
    )
    op.drop_table('movie_with_director')
    # ### end Alembic commands ###
