"""테이블이 잘못되어 새로 시작.

Revision ID: 729dd97efd83
Revises: 
Create Date: 2019-01-22 01:29:55.399485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729dd97efd83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=True),
    sa.Column('name_kr', sa.String(length=120), nullable=True),
    sa.Column('photo', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('director',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=True),
    sa.Column('name_kr', sa.String(length=120), nullable=True),
    sa.Column('photo', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=True),
    sa.Column('name_kr', sa.String(length=120), nullable=True),
    sa.Column('photo', sa.String(length=120), nullable=True),
    sa.Column('image_file_name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actor_association',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], )
    )
    op.create_table('cookie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description_en', sa.String(length=120), nullable=True),
    sa.Column('description_kr', sa.String(length=120), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie_with_director',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('director_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['director_id'], ['director.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_with_director')
    op.drop_table('cookie')
    op.drop_table('actor_association')
    op.drop_table('movie')
    op.drop_table('director')
    op.drop_table('actor')
    # ### end Alembic commands ###
