"""movies table

Revision ID: bfb1cf76e323
Revises: f267ad7666ad
Create Date: 2018-09-06 20:29:13.008882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfb1cf76e323'
down_revision = 'f267ad7666ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_name_en', sa.String(length=120), nullable=True),
    sa.Column('director_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['director_id'], ['director.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_movie_name_en'), 'movie', ['movie_name_en'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_movie_name_en'), table_name='movie')
    op.drop_table('movie')
    # ### end Alembic commands ###
