"""감독에 사진 항목 추가.

Revision ID: fbaf9a2c88dd
Revises: ec989e1e19f0
Create Date: 2018-09-15 22:33:59.749689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbaf9a2c88dd'
down_revision = 'ec989e1e19f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('director', sa.Column('photo', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('director', 'photo')
    # ### end Alembic commands ###
